---
# Default values for eck-logstash.
# This is a YAML-formatted file.

# Overridable names of the Logstash resource.
# By default, this is the Release name set for the chart,
# followed by 'eck-logstash'.
#
# nameOverride will override the name of the Chart with the name set here,
# so nameOverride: quickstart, would convert to '{{ Release.name }}-quickstart'
#
# nameOverride: "quickstart"
#
# fullnameOverride will override both the release name, and the chart name,
# and will name the Logstash resource exactly as specified.
#
# fullnameOverride: "quickstart"

# Version of Logstash.
#
version: 8.17.4

# Logstash Docker image to deploy
#
# image:

# Used to check access from the current resource to a resource (for ex. a remote Elasticsearch cluster) in a different namespace.
# Can only be used if ECK is enforcing RBAC on references.
#
# serviceAccountName: ""

# Labels that will be applied to Logstash.
#
labels: {}

# Annotations that will be applied to Logstash.
#
annotations: {}

# Number of revisions to retain to allow rollback in the underlying StatefulSets.
# By default, if not set, Kubernetes sets 10.
#
# revisionHistoryLimit: 2

# Controlling the number of pods.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-scaling-logstash.html
#
count: 1

# The logstash configuration, the ECK equivalent to logstash.yml
#
# NOTE: The `config` and `configRef` fields are mutually exclusive. Only one of them should be defined at a time,
# as using both may cause conflicts.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-configuring-logstash
#
config: {}

# Reference a configuration in a Secret.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-configuring-logstash
#
# configRef:
#   secretName: ''

# Set podTemplate to customize the pod used by Logstash
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-customize-pods.html
#
podTemplate: 
 spec:
  containers:
  - env:
    - name: LS_JAVA_OPTS
      value: -Xmx2g -Xms2g
    name: logstash
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: "500m"
        memory: 2Gi
    volumeMounts:
    - mountPath: /usr/share/logstash/pipeline/inputs/beats-input.conf
      name: logstash-beats-input
      subPath: beats-input.conf
    - mountPath: /usr/share/logstash/pipeline/outputs/logstash-kubernetes-cluster-output-pipeline.conf
      name: logstash-kubernetes-cluster-output-pipeline
      subPath: logstash-kubernetes-cluster-output-pipeline.conf
    - mountPath: /usr/share/logstash/pipeline/outputs/coredns-output.conf
      name: logstash-coredns-output
      subPath: coredns-output.conf
    - mountPath: /usr/share/logstash/pipeline/outputs/kube-apiserver-output.conf
      name: logstash-kube-apiserver-output
      subPath: kube-apiserver-output.conf
    - mountPath: /usr/share/logstash/pipeline/outputs/oarm-application-logs.conf
      name: oarm-application-logs
      subPath: oarm-application-logs.conf
  volumes:
  - name: logstash-beats-input
    secret:
      secretName: logstash-beats-input
  - name: logstash-kubernetes-cluster-output-pipeline
    secret:
      secretName: logstash-kubernetes-cluster-output-pipeline
  - name: logstash-coredns-output
    secret:
      secretName: logstash-coredns-output
  - name: logstash-kube-apiserver-output
    secret:
      secretName: logstash-kube-apiserver-output
  - name: oarm-application-logs
    secret:
      secretName: oarm-application-logs
  
  initContainers:
   - command:
     - sh
     - -c
     - chown -R 1000:1000 /usr/share/logstash/data
     - chmod -R 777 /usr/share/logstash/data
     name: fix-permissions
     image: container-registry.example.com/busybox:latest
     imagePullPolicy: IfNotPresent
     securityContext:
       privileged: true
       runAsUser: 0


# Settings for configuring stack monitoring.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html
#
monitoring: {}
  # metrics:
  #   elasticsearchRefs:
  #   - name: monitoring
  #     namespace: observability 
  # logs:
  #   elasticsearchRefs:
  #   - name: monitoring
  #     namespace: observability

# The Logstash pipelines, the ECK equivalent to pipelines.yml
#
# NOTE: The `pipelines` and `pipelinesRef` fields are mutually exclusive. Only one of them should be defined at a time,
# as using both may cause conflicts.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-pipelines
#
pipelines:
  - path.config: /usr/share/logstash/pipeline/inputs/beats-input.conf
    pipeline.id: main
  - path.config: /usr/share/logstash/pipeline/outputs/logstash-kubernetes-cluster-output-pipeline.conf         
    pipeline.id: logstash-kubernetes-cluster-output-pipeline
  - path.config: /usr/share/logstash/pipeline/outputs/coredns-output.conf
    pipeline.id: coredns
  - path.config: /usr/share/logstash/pipeline/outputs/kube-apiserver-output.conf
    pipeline.id: kubeapiserver
  - path.config: /usr/share/logstash/pipeline/outputs/oarm-application-logs.conf
    pipeline.id: oarm-application-logs


# Reference a pipelines configuration in a Secret.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-pipelines
#
# pipelinesRef:
#   secretName: ''

# volumeClaimTemplates
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-volume-claim-settings
#
volumeClaimTemplates:
- metadata:
    name: logstash-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-storage


# ElasticsearchRefs are references to Elasticsearch clusters running in the same Kubernetes cluster.
# Ensure that the 'clusterName' field matches what is referenced in the pipeline.
# ref: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-pipelines-es
#
elasticsearchRefs:
 - namespace: elastic-system
   name: elasticsearch-eck-elasticsearch
   clusterName: elasticsearch-eck-elasticsearch
#  serviceName: elasticsearch-eck-elasticsearch-es-http
#  secretName: elasticsearch-eck-elasticsearch-es-elastic-user

services: []

# SecureSettings is a list of references to Kubernetes Secrets containing sensitive configuration options for the Logstash
secureSettings: []

