apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticmasternodepv01
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    path: /nfs_data/ElasticSearch_data/ElasticMasterNode01
    server: 172.16.0.17

         
        
