apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticdatanodepv01
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs: 
    path: /nfs_data/ElasticSearch_data/ElasticDataNode01
    server: 172.16.0.17  

         
        
