apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
  podTemplate:
   spec:
    containers:
    - name: kibana
      resources:
       limits:
        cpu: 2
        memory: 4Gi
       requests:
        cpu: 2
        memory: 4Gi

