apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstashnodepv01
spec:
  capacity:
    storage: 7Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs: 
    path: /nfs_data/ElasticSearch_data/LogstashNode01
    server: 172.16.0.17

         
        
