apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv-02
spec:
  storageClassName: nfs-static
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.16.0.17           # Replace with your master node (NFS server) IP
    path: /nfs_data/prometheus-server/node02       # Replace with exported NFS path
  persistentVolumeReclaimPolicy: Retain

