grafana: 
 persistence:
    enabled: true
    type: sts
    storageClassName: "nfs-storage"
     accessModes:
       - ReadWriteOnce
     size: 20Gi
     finalizers:
       - kubernetes.io/pvc-protection
global:
  imageRegistry: local-container-registry:5000
prometheus:
 prometheusSpec:
  replicas: 2
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: nfs-storage
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

                  
